# Generated by Django 4.1.4 on 2022-12-20 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='balans_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balans_1', related_query_name='balans_1', to='docker_docker_admin.balans'),
        ),
        migrations.AddField(
            model_name='trade',
            name='balans_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balans_2', related_query_name='balans_2', to='docker_docker_admin.balans'),
        ),
    ]
