# Generated by Django 4.1.4 on 2022-12-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0003_price_total_price_price_total_price_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
