# Generated by Django 4.1.4 on 2022-12-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0004_remove_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='total_price_is_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
    ]
