# Generated by Django 4.1.4 on 2022-12-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0006_remove_price_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
    ]
