# Generated by Django 4.1.4 on 2022-12-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0007_alter_offer_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_active',
        ),
    ]
