# Generated by Django 4.1.4 on 2022-12-22 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0008_remove_offer_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
