# Generated by Django 4.1.4 on 2022-12-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0009_alter_offer_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='price',
            name='total_price_item',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
    ]
