# Generated by Django 4.1.4 on 2022-12-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0012_remove_trade_item_remove_trade_item_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='price_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price_total_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=5, null=True),
        ),
    ]
