# Generated by Django 4.1.4 on 2022-12-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0014_trade_ostatok_balanc_trade_ostatok_balanc_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='item_user_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
