# Generated by Django 4.1.4 on 2022-12-25 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0016_alter_watchlist_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='item_user_name',
        ),
    ]
