# Generated by Django 4.1.4 on 2022-12-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0017_remove_watchlist_item_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='price',
        ),
        migrations.AddField(
            model_name='inventory',
            name='name_item',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
