# Generated by Django 4.1.4 on 2022-12-25 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0018_remove_inventory_item_remove_inventory_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_name_3', related_query_name='item_name_3', to='docker_docker_admin.item'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='item_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_name_2', related_query_name='item_name_2', to='docker_docker_admin.item'),
        ),
    ]
