# Generated by Django 4.1.4 on 2022-12-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_docker_admin', '0019_inventory_item_inventory_item_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='item',
            new_name='count_item',
        ),
    ]
